"""Tests for src/collections/graphify_outputs — SCN-3.2."""

import json

import pytest

from src.collections.graphify_outputs import (
    COLLECTION_NAME,
    DEFAULT_ROUTING_HINT,
    REPORT_ROUTING_HINT,
    register_collection,
    scan_and_register,
)
from src.project import build_l0_content, generate_l0
from src.registry import create_collection, get_collection, query_documents
from src.routing import parse_route_hint


# ── Fixtures ─────────────────────────────────────────────────


@pytest.fixture
def graphify_tree(tmp_path):
    """Minimal repo tree with graphify-out/ artifacts."""
    graphify_dir = tmp_path / "graphify-out"
    graphify_dir.mkdir()

    (graphify_dir / "GRAPH_REPORT.md").write_text(
        "# Graph Report\n\nGenerated by graphify v1.0.0\n"
    )
    graph_data = {
        "graph_version": "sha256:abc123def456",
        "source_repo": "test-repo",
        "run_date": "2026-04-20",
        "nodes": [],
        "edges": [],
    }
    (graphify_dir / "graph.json").write_text(json.dumps(graph_data))
    return tmp_path


@pytest.fixture
def graphify_tree_no_graph_json(tmp_path):
    """Repo with only GRAPH_REPORT.md (no graph.json)."""
    graphify_dir = tmp_path / "graphify-out"
    graphify_dir.mkdir()
    (graphify_dir / "GRAPH_REPORT.md").write_text("# Graph Report\n")
    return tmp_path


# ── Collection registration ───────────────────────────────────


class TestRegisterCollection:
    def test_creates_collection(self, db_conn):
        cid = register_collection(db_conn)
        assert len(cid) == 26
        col = get_collection(db_conn, COLLECTION_NAME)
        assert col is not None
        assert col["name"] == COLLECTION_NAME

    def test_idempotent(self, db_conn):
        cid1 = register_collection(db_conn)
        cid2 = register_collection(db_conn)
        assert cid1 == cid2

    def test_config_has_correct_doc_types(self, db_conn):
        register_collection(db_conn)
        col = get_collection(db_conn, COLLECTION_NAME)
        assert "graph-report" in col["config"]["doc_types"]
        assert "graph-data" in col["config"]["doc_types"]


# ── SCN-3.2-01: scan registers GRAPH_REPORT.md and graph.json ─


class TestScanAndRegister:
    def test_registers_both_artifacts(self, db_conn, graphify_tree):
        results = scan_and_register(db_conn, graphify_tree)
        assert len(results) == 2
        types = {r["doc_type"] for r in results}
        assert types == {"graph-report", "graph-data"}

    def test_tags_source_repo(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        docs = query_documents(db_conn, collection_name=COLLECTION_NAME, tags={"source_repo": "test-repo"})
        assert len(docs) == 2

    def test_tags_graph_version(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        docs = query_documents(db_conn, collection_name=COLLECTION_NAME)
        for doc in docs:
            assert "graph_version" in doc["tags"]
            assert "sha256:abc123def456" in doc["tags"]["graph_version"]

    def test_tags_routing_hint(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        docs = query_documents(
            db_conn, collection_name=COLLECTION_NAME,
            tags={"routing_hint": DEFAULT_ROUTING_HINT},
        )
        assert len(docs) == 2

    def test_no_graphify_dir_returns_empty(self, db_conn, tmp_path):
        results = scan_and_register(db_conn, tmp_path)
        assert results == []

    def test_idempotent(self, db_conn, graphify_tree):
        r1 = scan_and_register(db_conn, graphify_tree)
        r2 = scan_and_register(db_conn, graphify_tree)
        assert len(r1) == 2
        assert len(r2) == 0

    def test_registers_only_report_when_no_graph_json(self, db_conn, graphify_tree_no_graph_json):
        results = scan_and_register(db_conn, graphify_tree_no_graph_json)
        assert len(results) == 1
        assert results[0]["doc_type"] == "graph-report"


# ── SCN-3.2-01: routing hint appears in L0 ───────────────────


class TestRoutingHintInL0:
    def test_l0_contains_routing_hint_after_scan(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        l0 = build_l0_content(db_conn)
        assert DEFAULT_ROUTING_HINT in l0
        assert "- route:" not in l0

    def test_l0_has_no_routing_section_without_graphify(self, db_conn):
        l0 = build_l0_content(db_conn)
        assert "Routing hints" not in l0

    def test_l0_routing_section_present_with_graphify(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        l0 = build_l0_content(db_conn)
        assert "## Routing hints" in l0

    def test_rendered_l0_route_lines_round_trip_through_parser(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        l0 = build_l0_content(db_conn)
        route_lines = [line for line in l0.splitlines() if line.startswith("route: ")]
        assert route_lines == [DEFAULT_ROUTING_HINT]
        parsed = parse_route_hint(route_lines[0])
        assert parsed["tentacle"] == "graphify.query"
        assert parsed["target"] == "graphify-out/graph.json"

    def test_report_only_mode_emits_graphify_report_route(self, db_conn, graphify_tree_no_graph_json):
        scan_and_register(db_conn, graphify_tree_no_graph_json)
        l0 = build_l0_content(db_conn)
        route_lines = [line for line in l0.splitlines() if line.startswith("route: ")]
        assert route_lines == [REPORT_ROUTING_HINT]
        parsed = parse_route_hint(route_lines[0])
        assert parsed["tentacle"] == "graphify.report"
        assert parsed["target"] == "graphify-out/GRAPH_REPORT.md"

    def test_empty_collections_are_hidden_from_l0_registry(self, db_conn, graphify_tree):
        create_collection(
            db_conn, "empty-collection", "Empty",
            config={"doc_types": ["note"], "statuses": ["active"]},
        )
        scan_and_register(db_conn, graphify_tree)
        l0 = build_l0_content(db_conn)
        assert "**empty-collection**" not in l0


# ── collectionStrategy variants ──────────────────────────────


class TestCollectionStrategy:
    def test_split_creates_graphify_outputs_collection(self, db_conn, graphify_tree):
        results = scan_and_register(db_conn, graphify_tree, collection_strategy="split")
        assert len(results) == 2
        col = get_collection(db_conn, COLLECTION_NAME)
        assert col is not None

    def test_unified_registers_into_target_collection(self, db_conn, graphify_tree):
        create_collection(
            db_conn, "parent-collection", "Parent",
            config={"doc_types": ["graph-report", "graph-data"], "statuses": ["active"]},
        )
        results = scan_and_register(
            db_conn, graphify_tree,
            collection_strategy="unified",
            target_collection="parent-collection",
        )
        assert len(results) == 2
        docs = query_documents(db_conn, collection_name="parent-collection")
        assert len(docs) == 2

    def test_unified_no_separate_graphify_collection_created(self, db_conn, graphify_tree):
        create_collection(
            db_conn, "parent-collection", "Parent",
            config={"doc_types": ["graph-report", "graph-data"], "statuses": ["active"]},
        )
        scan_and_register(
            db_conn, graphify_tree,
            collection_strategy="unified",
            target_collection="parent-collection",
        )
        # graphify-outputs collection was NOT auto-created
        assert get_collection(db_conn, COLLECTION_NAME) is None

    def test_unified_missing_target_raises(self, db_conn, graphify_tree):
        with pytest.raises(ValueError, match="does not exist"):
            scan_and_register(
                db_conn, graphify_tree,
                collection_strategy="unified",
                target_collection="nonexistent",
            )

    def test_unified_routing_hint_in_l0(self, db_conn, graphify_tree):
        create_collection(
            db_conn, "parent-collection", "Parent",
            config={"doc_types": ["graph-report", "graph-data"], "statuses": ["active"]},
        )
        scan_and_register(
            db_conn, graphify_tree,
            collection_strategy="unified",
            target_collection="parent-collection",
        )
        l0 = build_l0_content(db_conn)
        assert DEFAULT_ROUTING_HINT in l0

    def test_manifest_unified_strategy_is_honored(self, db_conn, graphify_tree):
        (graphify_tree / "governance.yaml").write_text(
            "graphify:\n"
            "  collectionStrategy: unified\n"
            "  sourceRepoTag: policy-repo\n"
        )
        parent_collection = graphify_tree.name
        create_collection(
            db_conn, parent_collection, "Parent",
            config={"doc_types": ["graph-report", "graph-data"], "statuses": ["active"]},
        )
        results = scan_and_register(db_conn, graphify_tree)
        assert len(results) == 2
        assert get_collection(db_conn, COLLECTION_NAME) is None
        docs = query_documents(db_conn, collection_name=parent_collection)
        assert len(docs) == 2

    def test_manifest_source_repo_tag_overrides_graph_json(self, db_conn, graphify_tree):
        (graphify_tree / "governance.yaml").write_text(
            "graphify:\n"
            "  collectionStrategy: split\n"
            "  sourceRepoTag: policy-repo\n"
        )
        scan_and_register(db_conn, graphify_tree)
        docs = query_documents(db_conn, collection_name=COLLECTION_NAME, tags={"source_repo": "policy-repo"})
        assert len(docs) == 2

    def test_rescan_refreshes_graph_metadata_tags(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        graph_json = graphify_tree / "graphify-out" / "graph.json"
        graph_json.write_text(json.dumps({
            "graph_version": "sha256:updated",
            "graph_schema_version": "v2",
            "source_repo": "test-repo",
            "run_date": "2026-04-21",
            "nodes": [],
            "edges": [],
        }))
        scan_and_register(db_conn, graphify_tree)
        docs = query_documents(db_conn, collection_name=COLLECTION_NAME, tags={"graph_version": "sha256:updated"})
        assert len(docs) == 2
        docs = query_documents(db_conn, collection_name=COLLECTION_NAME, tags={"graph_schema_version": "v2"})
        assert len(docs) == 2


class TestRoutingGrammar:
    def test_routing_hint_parses(self, db_conn, graphify_tree):
        scan_and_register(db_conn, graphify_tree)
        parsed = parse_route_hint(DEFAULT_ROUTING_HINT)
        assert parsed["tentacle"] == "graphify.query"
        assert parsed["target"] == "graphify-out/graph.json"
        assert parsed["budget"] == "6000"
